name: cargo-test

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  macos:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: >
          --features=source
          --no-default-features
          --manifest-path=metis/Cargo.toml

  linux:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        feature:
          - source
          - system
    steps:
    - uses: actions/checkout@v1
    - name: Install metis by apt
      run: |
        sudo apt update
        sudo apt install -y libmetis-dev
      if: ${{ matrix.feature == 'system' }}
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: >
          --features=${{ matrix.feature }}
          --no-default-features
          --manifest-path=metis/Cargo.toml

  check-format:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
